# Introduction

This is a book created from markdown and executable code.

GH Actions is working but now need to create a preview local & then upload it fully there.

0) https://www.youtube.com/watch?v=arzBRW5XIkg

1) Create `fbook` book project in quarto
2) No need to render it locally. Perhaps only preview.
3) `git init` & add required token, `user.name` & `user.email`
4) Create repo on GH `fbook`
5) Type this: 
```
git remote add origin https://github.com/fortunewalla/fbook.git
git branch -M main

```
6) git add . && git commmit -m "initial" & git push -u origin main

7) git add . && git commmit -m "initial" & git push --set-upstream origin main

8) Create `gh-pages` branch in GH repo.

9) mkdir & create file .github/workflows/publish-quarto.yml

10) GH Actions File. Don't copy the file from GH Actions Samples Example repo. It has some YAML error.
The below works.

```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true
          
      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
		  
```
10) Add requirments.txt file in root with `matplotlib`

11) Add `renv.lock` file in root.

```xml
{
  "R": {
    "Version": "4.4.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "markdown": {
      "Package": "markdown",
      "Version": "1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4584a57f565dd7987d59dda3a02cfb41"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.12.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "yihui",
      "RemoteRepo": "mime",
      "RemoteRef": "main",
      "RemoteSha": "1763e0dcb72fb58d97bab97bb834fc71f1e012bc",
      "Requirements": [
        "tools"
      ],
      "Hash": "c2772b6269924dad6784aaa1d99dbb86"
    }
  }
}

```
11.1) Fill up the `requirements.txt` & `renv.lock` based on your needs. The above are put just to make the workflow finish up.

11) git add . && git commmit -m "added publish-quarto.yml" & git push -u origin main

12) GH Settings -> Pages -> Branch change to `gh-pages` & directory as `/root` and then save.

13) It will start building & deploying to `gh-pages`




See @knuth84 for additional discussion of literate programming.
